[package]
name = "rwtfinspect"
description = "Inspect RWTF Files"
version = "0.1.0"
authors = ["Dan Larkin <dan@danlarkin.org>"]
license = "Apache-2.0 OR MIT"
edition = "2021"

[dependencies]
base64 = "0.13"
flate2 = "1.0"
tracklib2 = {path = "../tracklib2", features=["inspect"]}
