[package]
name = "ruby_tracklib"
version = "2.0.0"
edition = "2021"

[lib]
name = "ruby_tracklib"
crate-type = ["cdylib", "lib"]

[dependencies]
lazy_static = "1.4"
ouroboros = "0.15"
rutie = "0.8"
tracklib = {path="../tracklib"}
