# coding: utf-8
require "rbconfig"
require "bundler/gem_tasks"
require "rake/testtask"
require "thermite/tasks"
require 'rspec/core/rake_task'

thermite = Thermite::Tasks.new
RSpec::Core::RakeTask.new(:spec)

desc 'Run Rust & Ruby testsuites'
task test: ['thermite:build', 'thermite:test', 'spec'] do

end

task :default => :test
