[package]
name = "ruby_tracklib_next"
version = "0.1.0"
edition = "2021"

[lib]
name = "ruby_tracklib_next"
crate-type = ["cdylib", "lib"]

[dependencies]
lazy_static = "1.4"
ouroboros = "0.15"
rutie = "0.8"
tracklib2 = {path="../tracklib2"}
